version: "3.9"

services:
  backend:
    build: ./backend
    container_name: ccna-backend

  caddy:
    image: caddy:2
    container_name: ccna-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend

volumes:
  caddy_data:
  caddy_config: